bicep refmt
The formatting changed in the latest release...
https://github.com/Azure/bicep/releases/tag/v0.27.1

Signed-off-by: Michael Shen <mshen@redhat.com>

diff --git a/.github/workflows/dev-infrastructure.yml b/.github/workflows/dev-infrastructure.yml
--- a/.github/workflows/dev-infrastructure.yml
+++ b/.github/workflows/dev-infrastructure.yml
@@ -27,10 +27,11 @@ jobs:
       - name: 'az bicep format and lint'
         working-directory: './dev-infrastructure'
         run: |
+          az bicep version
           make fmt
           make lint
 
       - name: Check for uncommitted changes
         working-directory: './dev-infrastructure'
         run: |
-          git diff --exit-code || (echo "::error::Uncommitted changes detected in OpenAPI spec. Please regenerate and commit them." && exit 1)
+          git diff --exit-code || (echo "::error::Uncommitted changes detected in bicep templates" && exit 1)
